using System.Globalization;
using System.Text;
using System.Xml.Linq;
using IS2Mod.ControlTypes;
using ModernVintageGUI.ControlTypes;

namespace ModernVintageGUI.Designer.Markup
{
    /// <summary>
    /// Writes the C# that builds the document's tree.
    ///
    /// The framework is used from code today, so a design is only useful once it can leave the
    /// designer as code. This emits the same shape the scenarios and the showcase are written
    /// in - construct, set, add to the parent - rather than anything the designer would have to
    /// be present to run.
    /// </summary>
    public static class CodeGenerator
    {
        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        public static string Generate(DesignDocument document, string methodName = "Build")
        {
            XElement? root = document.Xml.Root;

            var sb = new StringBuilder();

            sb.AppendLine("// Generated by the ModernVintageGUI designer.");
            sb.AppendLine("using Cairo;");
            sb.AppendLine("using IS2Mod.ControlTypes;");
            sb.AppendLine("using IS2Mod.Enums;");
            sb.AppendLine("using ModernVintageGUI.ControlTypes;");
            sb.AppendLine();
            sb.AppendLine($"public static UIControl {methodName}()");
            sb.AppendLine("{");

            if (root == null)
            {
                sb.AppendLine("    return new RectangleControl();");
                sb.AppendLine("}");
                return sb.ToString();
            }

            var names = new Dictionary<string, int>(StringComparer.Ordinal);
            string rootVariable = Emit(sb, root, parent: null, names, indent: 1);

            sb.AppendLine();
            sb.AppendLine($"    return {rootVariable};");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>Writes one element and its children, and returns the variable it landed in.</summary>
        private static string Emit(
            StringBuilder sb, XElement element, string? parent, Dictionary<string, int> names, int indent)
        {
            string pad = new string(' ', indent * 4);

            if (string.Equals(element.Name.LocalName, ControlCatalog.TabTag, StringComparison.OrdinalIgnoreCase))
            {
                // Handled by the Tabs branch of its parent.
                return "";
            }

            ControlDescriptor? descriptor = ControlCatalog.Get(element.Name.LocalName);

            if (descriptor == null)
            {
                sb.AppendLine($"{pad}// unknown control <{element.Name.LocalName}>, skipped");
                return "";
            }

            string variable = Variable(element, descriptor, names);
            string type = descriptor.ClrType.Name;

            sb.AppendLine();
            sb.AppendLine($"{pad}var {variable} = new {type}();");

            foreach (XAttribute attribute in element.Attributes())
            {
                MarkupProperty? property = descriptor.Find(attribute.Name.LocalName);
                if (property == null)
                    continue;

                if (!ValueConverters.TryParse(property.Type, attribute.Value, out object? value, out _))
                    continue;

                sb.AppendLine($"{pad}{variable}.{property.Name} = {Literal(property.Type, value)};");
            }

            // The parser reads a written size the way the constructors do; the generated code
            // has to say so out loud, because the Size setter on its own does not.
            if (element.Attribute("Size") != null && element.Attribute("IsAutoSize") == null)
            {
                sb.AppendLine($"{pad}{variable}.IsAutoSize = false;");
            }

            if (descriptor.ClrType == typeof(TabsControl))
            {
                EmitTabs(sb, element, variable, names, indent);
            }
            else if (descriptor.AcceptsChildren)
            {
                foreach (XElement child in element.Elements())
                {
                    string childVariable = Emit(sb, child, variable, names, indent);

                    if (childVariable.Length > 0)
                        sb.AppendLine($"{pad}{variable}.Children.Add({childVariable});");
                }
            }

            return variable;
        }

        private static void EmitTabs(
            StringBuilder sb, XElement element, string variable, Dictionary<string, int> names, int indent)
        {
            string pad = new string(' ', indent * 4);

            foreach (XElement page in element.Elements())
            {
                if (!string.Equals(page.Name.LocalName, ControlCatalog.TabTag, StringComparison.OrdinalIgnoreCase))
                    continue;

                string caption = (string?)page.Attribute("Caption") ?? "Tab";
                XElement? content = page.Elements().FirstOrDefault();

                if (content == null)
                {
                    sb.AppendLine($"{pad}{variable}.AddTab({Quote(caption)});");
                    continue;
                }

                string contentVariable = Emit(sb, content, variable, names, indent);
                sb.AppendLine($"{pad}{variable}.AddTab({Quote(caption)}, {contentVariable});");
            }
        }

        /// <summary>A variable name from the control's Name, or from its type when it has none.</summary>
        private static string Variable(XElement element, ControlDescriptor descriptor, Dictionary<string, int> names)
        {
            string stem = (string?)element.Attribute("Name") ?? "";

            stem = new string(stem.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());

            if (stem.Length == 0 || char.IsDigit(stem[0]))
                stem = char.ToLowerInvariant(descriptor.Tag[0]) + descriptor.Tag.Substring(1) + stem;

            stem = char.ToLowerInvariant(stem[0]) + stem.Substring(1);

            names.TryGetValue(stem, out int count);
            names[stem] = count + 1;

            return count == 0 ? stem : stem + (count + 1);
        }

        private static string Literal(Type type, object? value)
        {
            switch (value)
            {
                case null:
                    return "null";
                case string s:
                    return Quote(s);
                case bool b:
                    return b ? "true" : "false";
                case int i:
                    return i.ToString(Inv);
                case double d:
                    return d.ToString("0.####", Inv);
                case float f:
                    return f.ToString("0.####", Inv) + "f";
                case Cairo.PointD p:
                    return $"new PointD({p.X.ToString("0.####", Inv)}, {p.Y.ToString("0.####", Inv)})";
                case ElementColor c:
                    return $"new ElementColor((byte){c.R}, (byte){c.G}, (byte){c.B}, (byte){c.A})";
                case Enum e:
                    return type.Name + "." + e;
                default:
                    return Quote(value.ToString() ?? "");
            }
        }

        private static string Quote(string text)
        {
            return "\"" + text
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }
    }
}
